### PR TITLE
chore: update to build with rust 1.80

### PR DESCRIPTION
**Pull request by chenrui333**
seeing some time related failure 

```
error[E0282]: type annotations needed for `Box<_>`
  --> /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.31/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++
```

has been addressed with 0.3.36, https://github.com/time-rs/time/issues/693

### CODE REVIEW

**Comment by martinthonon** [comment]
Maybe you should add time to dependencies in Cargo.toml instead of reformatting some lines.
``` 
[dependencies]
blake2-rfc = "0.2"
chrono = "0.4.11"
clap = { version = "2.33", features = ["yaml"] }
ctrlc = { version = "3.1", features = ["termination"] }
cursive_table_view = "0.14.0"
humansize = "1.1.0"
serde = "1"
futures = "0.3.19"
serde_json = "1"
log = "0.4"
term = "0.6"
time = "0.3.36"
```

**Comment by yeastplume** [comment]
Thanks for pointing this out, it's actually cursive that includes the broken dependency and needs to be updated, so I'm just doing that in another PR.

**Comment by chenrui333** [comment]
any interest of merging this PR?

**Comment by yeastplume** [comment]
@chenrui333 Thanks for pointing this out, it's covered in #3796 and I'll be doing a new release soon

**Comment by chenrui333** [comment]
Thanks @yeastplume!
