### ISSUE TITLE
error: failed to run custom build command for `croaring-sys v0.3.5`

### ISSUE THREAD

**Issue by peitalin** [mimblewimble/grin#1263]
Docker build works, however when I try build with `cargo build` I run into any error:
`error: failed to run custom build command for 'croaring-sys v0.3.5'`

Unsure what exactly is causing this, some additional error messages:
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include/fmaintrin.h:127:10: error: invalid conversion between vector type '__m128d' (vector of 2 'double' values) and integer type 'int' of different size, err: true
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include/fmaintrin.h:145:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size, err: true
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include/fmaintrin.h:151:10: error: invalid conversion between vector type '__m128d' (vector of 2 'double' values) and integer type 'int' of different size, err: true
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include/fmaintrin.h:169:10: error: invalid conversion between vector type '__m256' (vector of 8 'float' values) and integer type 'int' of different size, err: true
fatal error: too many errors emitted, stopping now [-ferror-limit=], err: true
thread 'main' panicked at 'Unable to generate bindings: ()', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by peitalin** [comment]
Updated llvm and developer tools and the issue went away.

**Comment by givanse** [comment]
I just saw the error in Ubuntu. The workaround for me was:

> sudo apt-get purge --auto-remove clang

original thread: https://github.com/saulius/croaring-rs/issues/34

**Comment by givanse** [comment]
In the issue saulius/croaring-rs#34 I found a workaround for Ubuntu 18.04:

> sudo apt-get purge --auto-remove clang

**Comment by MSauce** [comment]
Seeing similar: 
`error: failed to run custom build command for 'croaring-sys v0.3.6'`
`thread 'main' panicked at 'called 'Option::unwrap()' on a 'None' value', libcore/option.rs:345:21
note: Run with 'RUST_BACKTRACE=1' for a backtrace.`

on WSL Ubuntu 18.10 and neither updating llvm/dev tools nor sudo apt-get purge --auto-remove clang worked. Will try 18.04

**Comment by Onefox** [comment]
I have the same problem with ubuntu 16.04

**Comment by Scott-Sanderson** [comment]
Getting this error trying to build on 10.4.4. Is there a recommended way to update llvm?
