### ISSUE TITLE
Cannot compile grin_store master on MacOS

### ISSUE THREAD

**Issue by godzillou7563** [mimblewimble/grin#216]
On [7f8d307], I'm getting the following error compiling master with "cargo build":

   Compiling grin_store v0.1.0 (file:///Users/xyz/Documents/grin/store)
error[E0433]: failed to resolve. Could not find `Protection` in `memmap`
  --> store/src/sumtree.rs:87:25
   |
87 | 				.protection(memmap::Protection::Read)
   | 				                    ^^^^^^^^^^ Could not find `Protection` in `memmap`

error[E0425]: cannot find function `file` in module `memmap`
  --> store/src/sumtree.rs:86:12
   |
86 | 			memmap::file(&self.file)
   | 			        ^^^^ not found in `memmap`

error: aborting due to 2 previous errors

error: Could not compile `grin_store`.

**Comment by yeastplume** [comment]
I've just built the latest on MacOS and no issues, could you:

```
rustup update
```
```
cargo update
```
Then ensure you're running the latest code from the repository and try again?

**Comment by godzillou7563** [comment]
Still the same issue after updating. It seems that memmap-rs just updated their repo and grin only works with version 0.5.2.

**Comment by godzillou7563** [comment]
Tried to force memmap to be 0.5.2. I'm encountering some other compile time error:

error[E0425]: cannot find function `file` in module `memmap`
  --> store/src/sumtree.rs:86:12
   |
86 | 			memmap::file(&self.file)
   | 			        ^^^^ not found in `memmap`

error[E0608]: cannot index into a value of type `&memmap::Mmap`
   --> store/src/sumtree.rs:100:5
    |
100 | 		(&mmap[offset..(offset + length)]).to_vec()
    | 		  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `grin_store`.

Curious to know what version of memmap works.

**Comment by yeastplume** [comment]
Fix referenced above.. if you'd like to try earlier, you can pull from https://github.com/yeastplume/grin/tree/sumtree_mmap_fix

**Comment by godzillou7563** [comment]
Thanks. I've tested it on master and it worked fine.
