### ISSUE TITLE
Update rust version on build requirements

### ISSUE THREAD

**Issue by dagonharett** [mimblewimble/grin#3190]
The [build requirements](https://github.com/mimblewimble/grin/blob/master/doc/build.md#requirements) list `1.34` as the minimum rust version. However such rust version no longer works for grin [`v3.0.0`](https://github.com/mimblewimble/grin/releases/tag/v3.0.0). Building fails with the following error:

```
error[E0277]: the trait bound `std::string::String: std::convert::From<&std::string::String>` is not satisfied
  --> src/bin/tui/logs.rs:92:23
   |
92 |                 let log_message = StyledString::plain(&entry.log);
   |                                   ^^^^^^^^^^^^^^^^^^^ the trait `std::convert::From<&std::string::String>` is not implemented for `std::string::String`
   |
   = help: the following implementations were found:
             <std::string::String as std::convert::From<&'a str>>
             <std::string::String as std::convert::From<std::borrow::Cow<'a, str>>>
             <std::string::String as std::convert::From<std::boxed::Box<str>>>
   = note: required because of the requirements on the impl of `std::convert::Into<std::string::String>` for `&std::string::String`
   = note: required by `cursive::utils::markup::<impl cursive::utils::span::SpannedString<cursive::theme::style::Style>>::plain
```

Building with rust `1.37` worked out fine.

This kind of information is relevant for those using the packaged rust version on their distribution. Debian 10 (buster) includes rust `1.34`. Ubuntu 18.04 (bionic) has rust `1.37`.

**Comment by cadwgan0** [comment]
I was able to replicate your issue as well, submitted a potential fix after verifying I could build on 1.34.0

**Comment by dagonharett** [comment]
@cadwgan0 Thanks a lot for fixing it so quickly.

Cherry picking your commit (8568c77) on top of [`v3.0.0`](https://github.com/mimblewimble/grin/releases/tag/v3.0.0) works wonders and allowed me to build grin.

Unfortunately I cannot build master (currently at 8568c77) with rustc `1.34` due to some other issues that arise when compiling dependencies. I've changed this issue title and I am opening another one specifically for the problem with the dependencies.
