### ISSUE TITLE
need latest RUST upgrade to compile v4.0.x

### ISSUE THREAD

**Issue by MCM-Mike** [mimblewimble/grin#3375]
**Describe the bug**
if you do not upgrade to the latest RUST upgrade , at least on Debian 9 (Linux grinnode03 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1+deb9u1 (2020-06-07) x86_64 GNU/Linux) you will run into build error

```
error: cannot find macro `matches` in this scope
  --> /.cargo/registry/src/github.com-1ecc6299db9ec823/built-0.4.2/src/util.rs:84:32
   |
84 |                 .any(|status| !matches!(status.status(), git2::Status::CURRENT));
   |                                ^^^^^^^

error: aborting due to previous error

error: could not compile `built`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**To Reproduce**
1. Try to compile with rustc 1.39.0 (4560ea788 2019-11-04)
2. Expect 'see error above'

**Upgrade RUST**
based on https://doc.rust-lang.org/book/ch01-01-installation.html

```grinnode03:/opt/grin/build/grin# rustup update
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2020-06-18, rust version 1.44.1 (c7087fe00 2020-06-17)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
 60.3 MiB /  60.3 MiB (100 %)  55.8 MiB/s in  1s ETA:  0s
info: downloading component 'rustfmt'
info: removing previous version of component 'cargo'
info: removing previous version of component 'clippy'
info: removing previous version of component 'rust-docs'
info: removing previous version of component 'rust-std'
info: removing previous version of component 'rustc'
info: removing previous version of component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
 12.2 MiB /  12.2 MiB (100 %)   9.1 MiB/s in  1s ETA:  0s
info: installing component 'rust-std'
info: installing component 'rustc'
 60.3 MiB /  60.3 MiB (100 %)  14.5 MiB/s in  4s ETA:  0s
info: installing component 'rustfmt'
info: checking for self-updates
info: downloading self-update

  stable-x86_64-unknown-linux-gnu updated - rustc 1.44.1 (c7087fe00 2020-06-17)```

**Comment by antiochp** [comment]
Not strictly "latest" but `1.42` is required for the `matches!` macro which appears to be used in a dependency.

https://doc.rust-lang.org/beta/std/macro.matches.html

**Comment by antiochp** [comment]
https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1420-2020-03-12

**Comment by MCM-Mike** [comment]
> Not strictly "latest" but `1.42` is required for the `matches!` macro which appears to be used in a dependency.
> 
> https://doc.rust-lang.org/beta/std/macro.matches.html

thank you. 
I will now close this issue now.
